<?php

namespace Database\Seeders;

use Filament\Tables\Columns\Summarizers\Range;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Nette\Utils\Random;

class ExamQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("exam_questions")->insert([
            [
                "exam_category_id" => 1,
                "year" => "2004",
                "month" => "March",
                "image" => "null",
                "question" => "Which medication is commonly used to treat hypertension?",
                "option_a" => "a) Ibuprofen",
                "option_b" => "b) Lisinopril",
                "option_c" => "c) Metformin",
                "option_d" => "d) Insulin",
                "correct_answer" => "Answer: b) Lisinopril",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 1,
                "year" => "2006",
                "month" => "June",
                "image" => "null",
                "question" => "What is the mechanism of action of acetaminophen?",
                "option_a" => "a) Anti-inflammatory",
                "option_b" => "b) Antipyretic",
                "option_c" => "c) Antiplatelet",
                "option_d" => "d) Antibiotic",
                "correct_answer" => "Answer: b) Antipyretic",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 1,
                "year" => "2000",
                "month" => "January",
                "image" => "null",
                "question" => "Which medication is used to reverse opioid overdose?",
                "option_a" => "a) Naloxone",
                "option_b" => "b) Atropine",
                "option_c" => "c) Epinephrine",
                "option_d" => "d) Digoxin",
                "correct_answer" => "Answer: a) Naloxone",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 1,
                "year" => "2000",
                "month" => "February",
                "image" => "null",
                "question" => "What is the common side effect of nonsteroidal anti-inflammatory drugs (NSAIDs)?",
                "option_a" => "a) Hypertension",
                "option_b" => "b) Hypoglycemia",
                "option_c" => "c) Gastrointestinal bleeding",
                "option_d" => "d) Bradycardia",
                "correct_answer" => "Answer: c) Gastrointestinal bleeding",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 1,
                "year" => "2000",
                "month" => "February",
                "image" => "null",
                "question" => "What is the classification of insulin glargine?",
                "option_a" => "a) Rapid-acting insulin",
                "option_b" => "b) Short-acting insulin",
                "option_c" => "c) Intermediate-acting insulin",
                "option_d" => "d) Long-acting insulin",
                "correct_answer" => "Answer: d) Long-acting insulin",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 1,
                "year" => "2001",
                "month" => "May",
                "image" => "null",
                "question" => "Which medication is commonly used to treat depression?",
                "option_a" => "a) Metoprolol",
                "option_b" => "b) Lisinopril",
                "option_c" => "c) Sertraline",
                "option_d" => "d) Metformin",
                "correct_answer" => "Answer: c) Sertraline",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 1,
                "year" => "2001",
                "month" => "July",
                "image" => "null",
                "question" => "What is the primary action of statin medications?",
                "option_a" => "a) Lower blood pressure",
                "option_b" => "b) Lower cholesterol levels",
                "option_c" => "c) Increase insulin sensitivity",
                "option_d" => "d) Prevent blood clots",
                "correct_answer" => "Answer: b) Lower cholesterol levels",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 1,
                "year" => "2002",
                "month" => "July",
                "image" => "null",
                "question" => "What is the antidote for heparin overdose?",
                "option_a" => "a) Vitamin K",
                "option_b" => "b) Protamine sulfate",
                "option_c" => "c) Naloxone",
                "option_d" => "d) Flumazenil",
                "correct_answer" => "Answer: b) Protamine sulfate",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 1,
                "year" => "2002",
                "month" => "July",
                "image" => "null",
                "question" => "What is the common side effect of angiotensin-converting enzyme (ACE) inhibitors?",
                "option_a" => "a) Hyperkalemia",
                "option_b" => "b) Hypoglycemia",
                "option_c" => "c) Hypertension",
                "option_d" => "d) Bradycardia",
                "correct_answer" => "Answer: a) Hyperkalemia",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 1,
                "year" => "2010",
                "month" => "September",
                "image" => "null",
                "question" => "Which medication is used to treat bacterial infections?",
                "option_a" => "a) Prednisone",
                "option_b" => "b) Amoxicillin",
                "option_c" => "c) Metoprolol",
                "option_d" => "d) Aspirin",
                "correct_answer" => "Answer: b) Amoxicillin",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 2,
                "year" => "2010",
                "month" => "January",
                "image" => "null",
                "question" => "What is the priority nursing intervention for a patient with chest pain?",
                "option_a" => "a) Administering pain medication",
                "option_b" => "b) Placing the patient in a supine position",
                "option_c" => "c) Initiating cardiac monitoring",
                "option_d" => "d) Providing emotional support",
                "correct_answer" => "Answer: c) Initiating cardiac monitoring",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 2,
                "year" => "2011",
                "month" => "February",
                "image" => "null",
                "question" => "What is the purpose of incentive spirometry?",
                "option_a" => "a) To promote deep breathing and prevent pneumonia",
                "option_b" => "b) To assess neurological function",
                "option_c" => "c) To administer oxygen therapy",
                "option_d" => "d) To measure urine output",
                "correct_answer" => "Answer: a) To promote deep breathing and prevent pneumonia",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 2,
                "year" => "2012",
                "month" => "August",
                "image" => "null",
                "question" => "What is the priority nursing intervention for a patient with a nasogastric (NG) tube?",
                "option_a" => "a) Administering pain medication",
                "option_b" => "b) Securing the NG tube to prevent displacement",
                "option_c" => "c) Providing emotional support",
                "option_d" => "d) Initiating cardiac monitoring",
                "correct_answer" => "Answer: b) Securing the NG tube to prevent displacement",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 2,
                "year" => "2014",
                "month" => "October",
                "image" => "null",
                "question" => "What is a common complication of surgery?",
                "option_a" => "a) Decreased risk of infection",
                "option_b" => "b) Increased risk of blood clots",
                "option_c" => "c) Improved mobility",
                "option_d" => "d) Enhanced appetite",
                "correct_answer" => "Answer: b) Increased risk of blood clots",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 2,
                "year" => "2014",
                "month" => "December",
                "image" => "null",
                "question" => "What is the primary purpose of preoperative teaching?",
                "option_a" => "a) To administer medication",
                "option_b" => "b) To promote understanding and reduce anxiety",
                "option_c" => "c) To monitor vital signs",
                "option_d" => "d) To measure urine output",
                "correct_answer" => "Answer: b) To promote understanding and reduce anxiety",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 2,
                "year" => "2015",
                "month" => "January",
                "image" => "null",
                "question" => "What is a priority nursing intervention for a patient with a wound drain?",
                "option_a" => "a) Administering pain medication",
                "option_b" => "b) Monitoring for signs of infection",
                "option_c" => "c) Securing the drain to prevent displacement",
                "option_d" => "d) Initiating cardiac monitoring",
                "correct_answer" => "Answer: b) Monitoring for signs of infection",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 2,
                "year" => "2015",
                "month" => "February",
                "image" => "null",
                "question" => "What is the purpose of a Jackson-Pratt drain?",
                "option_a" => "a) To measure urine output",
                "option_b" => "b) To administer medication",
                "option_c" => "c) To monitor blood glucose levels",
                "option_d" => "d) To collect fluid from a surgical wound",
                "correct_answer" => "Answer: d) To collect fluid from a surgical wound",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 2,
                "year" => "2015",
                "month" => "March",
                "image" => "null",
                "question" => "What is the priority nursing intervention for a patient with a wound dehiscence?",
                "option_a" => "a) Administering pain medication",
                "option_b" => "b) Initiating cardiac monitoring",
                "option_c" => "c) Covering the wound with a dry dressing",
                "option_d" => "d) Notifying the physician immediately",
                "correct_answer" => "Answer: d) Notifying the physician immediately",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 2,
                "year" => "2015",
                "month" => "November",
                "image" => "null",
                "question" => "What is the primary purpose of postoperative ambulation?",
                "option_a" => "a) To promote deep breathing",
                "option_b" => "b) To prevent blood clots",
                "option_c" => "c) To assess neurological function",
                "option_d" => "d) To measure urine output",
                "correct_answer" => "Answer: b) To prevent blood clots",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 2,
                "year" => "2016",
                "month" => "January",
                "image" => "null",
                "question" => "What is the primary nursing intervention for a patient with a pressure ulcer?",
                "option_a" => "a) Administering pain medication",
                "option_b" => "b) Applying a transparent film dressing",
                "option_c" => "c) Keeping the wound dry",
                "option_d" => "d) Initiating cardiac monitoring",
                "correct_answer" => "Answer: c) Keeping the wound dry",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 3,
                "year" => "2017",
                "month" => "April",
                "image" => "null",
                "question" => "What is the largest organ in the human body?",
                "option_a" => "a) Liver",
                "option_b" => "b) Brain",
                "option_c" => "c) Skin",
                "option_d" => "d) Heart",
                "correct_answer" => "Answer: c) Skin",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 3,
                "year" => "2017",
                "month" => "December",
                "image" => "null",
                "question" => "Which part of the brain is responsible for regulating basic bodily functions such as breathing and heart rate?",
                "option_a" => "a) Cerebrum",
                "option_b" => "b) Cerebellum",
                "option_c" => "c) Medulla oblongata",
                "option_d" => "d) Hypothalamus",
                "correct_answer" => "Answer: c) Medulla oblongata",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 3,
                "year" => "2018",
                "month" => "January",
                "image" => "null",
                "question" => "Where are red blood cells produced in the body?",
                "option_a" => "a) Liver",
                "option_b" => "b) Kidneys",
                "option_c" => "c) Spleen",
                "option_d" => "d) Bone marrow",
                "correct_answer" => "Answer: d) Bone marrow",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 3,
                "year" => "2019",
                "month" => "January",
                "image" => "null",
                "question" => "What is the function of the alveoli in the respiratory system?",
                "option_a" => "a) Transport oxygen to the body",
                "option_b" => "b) Exchange oxygen and carbon dioxide",
                "option_c" => "c) Produce mucus to trap pathogens",
                "option_d" => "d) Pump blood to the lungs",
                "correct_answer" => "Answer: b) Exchange oxygen and carbon dioxide",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 3,
                "year" => "2019",
                "month" => "January",
                "image" => "null",
                "question" => "Which hormone is responsible for regulating blood sugar levels?",
                "option_a" => "a) Insulin",
                "option_b" => "b) Estrogen",
                "option_c" => "c) Testosterone",
                "option_d" => "d) Cortisol",
                "correct_answer" => "Answer: a) Insulin",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 3,
                "year" => "2020",
                "month" => "February",
                "image" => "null",
                "question" => "What is the purpose of the lymphatic system in the body?",
                "option_a" => "a) Transport oxygen to tissues",
                "option_b" => "b) Produce hormones",
                "option_c" => "c) Fight infection and remove excess fluid from tissues",
                "option_d" => "d) Pump blood to the heart",
                "correct_answer" => "Answer: c) Fight infection and remove excess fluid from tissues",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 3,
                "year" => "2020",
                "month" => "December",
                "image" => "null",
                "question" => "Which of the following is not a function of the skeletal system?",
                "option_a" => "a) Provide structure and support for the body",
                "option_b" => "b) Produce red blood cells",
                "option_c" => "c) Store minerals such as calcium and phosphorus",
                "option_d" => "d) Produce hormones",
                "correct_answer" => "Answer: d) Produce hormones",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 3,
                "year" => "2003",
                "month" => "December",
                "image" => "null",
                "question" => "What is the primary function of the digestive system?",
                "option_a" => "a) Transport oxygen to the body",
                "option_b" => "b) Break down food and absorb nutrients",
                "option_c" => "c) Produce hormones",
                "option_d" => "d) Control body temperature",
                "correct_answer" => "Answer: b) Break down food and absorb nutrients",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 3,
                "year" => "2004",
                "month" => "September",
                "image" => "null",
                "question" => "Which of the following is not a component of blood?",
                "option_a" => "a) Plasma",
                "option_b" => "b) Platelets",
                "option_c" => "c) Enzymes",
                "option_d" => "d) Red blood cells",
                "correct_answer" => "Answer: c) Enzymes",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 3,
                "year" => "2005",
                "month" => "September",
                "image" => "null",
                "question" => "Where is the pituitary gland located in the body?",
                "option_a" => "a) In the chest cavity",
                "option_b" => "b) In the abdomen",
                "option_c" => "c) In the brain",
                "option_d" => "d) In the neck",
                "correct_answer" => "Answer: c) In the brain",
                "user_id" => 1
            ],
            [
                "exam_category_id" => 4,
                "year" => "2007",
                "month" => "January",
                "image" => "null",
                "question" => "What is the proper technique for hand hygiene?",
                "option_a" => "a) Washing hands with water only",
                "option_b" => "b) Using hand sanitizer without water",
                "option_c" => "c) Washing hands with soap and water for at least 20 seconds",
                "option_d" => "d) Using gloves instead of hand hygiene",
                "correct_answer" => "Answer: c) Washing hands with soap and water for at least 20 seconds",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 4,
                "year" => "2008",
                "month" => "February",
                "image" => "null",
                "question" => "How often should a patient's vital signs be monitored in a stable condition?",
                "option_a" => "a) Every hour",
                "option_b" => "b) Every 4 hours",
                "option_c" => "c) Every 8 hours",
                "option_d" => "d) Every 24 hours",
                "correct_answer" => "Answer: b) Every 4 hours",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 4,
                "year" => "2009",
                "month" => "December",
                "image" => "null",
                "question" => "What is the normal range for body temperature in adults?",
                "option_a" => "a) 35-36°C (95-96.8°F)",
                "option_b" => "b) 36.5-37.5°C (97.7-99.5°F)",
                "option_c" => "c) 37.5-38.5°C (99.5-101.3°F)",
                "option_d" => "d) 38.5-39.5°C (101.3-103.1°F)",
                "correct_answer" => "Answer: b) 36.5-37.5°C (97.7-99.5°F)",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 4,
                "year" => "2010",
                "month" => "June",
                "image" => "null",
                "question" => "How should a nurse measure a patient's respiratory rate?",
                "option_a" => "a) Counting the number of breaths per minute",
                "option_b" => "b) Counting the number of breaths per hour",
                "option_c" => "c) Counting the number of breaths per 15 seconds and multiplying by 4",
                "option_d" => "d) Counting the number of breaths per 30 seconds and multiplying by 2",
                "correct_answer" => "Answer: c) Counting the number of breaths per 15 seconds and multiplying by 4",
                "user_id" => 2
            ],
            [
                "exam_category_id" => 4,
                "year" => "2019",
                "month" => "June",
                "image" => "null",
                "question" => "What is the purpose of a bedpan?",
                "option_a" => "a) To measure urine output",
                "option_b" => "b) To collect stool when a patient cannot use the toilet",
                "option_c" => "c) To administer medication",
                "option_d" => "d) To feed patients who cannot eat solid food",
                "correct_answer" => "Answer: b) To collect stool when a patient cannot use the toilet",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 4,
                "year" => "2020",
                "month" => "June",
                "image" => "null",
                "question" => "What is the correct procedure for measuring blood pressure?",
                "option_a" => "a) Inflate the cuff until the gauge reads 200 mmHg",
                "option_b" => "b) Place the stethoscope over the brachial artery",
                "option_c" => "c) Inflate the cuff 30 mmHg above the point where the pulse disappears",
                "option_d" => "d) Measure blood pressure only on the left arm",
                "correct_answer" => "Answer: b) Place the stethoscope over the brachial artery",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 4,
                "year" => "2021",
                "month" => "June",
                "image" => "null",
                "question" => "What should a nurse do if a patient complains of pain?",
                "option_a" => "a) Ignore the complaint if the patient appears comfortable",
                "option_b" => "b) Administer pain medication immediately",
                "option_c" => "c) Assess the pain using a pain scale and provide appropriate intervention",
                "option_d" => "d) Document the complaint and inform the physician during rounds",
                "correct_answer" => "Answer: c) Assess the pain using a pain scale and provide appropriate intervention",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 4,
                "year" => "2022",
                "month" => "June",
                "image" => "null",
                "question" => "What is the purpose of a Foley catheter?",
                "option_a" => "a) To administer medication",
                "option_b" => "b) To measure urine output",
                "option_c" => "c) To feed patients who cannot eat solid food",
                "option_d" => "d) To collect stool when a patient cannot use the toilet",
                "correct_answer" => "Answer: b) To measure urine output",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 4,
                "year" => "2023",
                "month" => "June",
                "image" => "null",
                "question" => "When should a nurse perform a skin assessment on a patient?",
                "option_a" => "a) Once a week",
                "option_b" => "b) Every shift",
                "option_c" => "c) Only when there are visible changes in the skin",
                "option_d" => "d) Never, as it is not a nursing responsibility",
                "correct_answer" => "Answer: b) Every shift",
                "user_id" => 3
            ],
            [
                "exam_category_id" => 4,
                "year" => "2024",
                "month" => "January",
                "image" => "null",
                "question" => "What is the purpose of a nasogastric tube?",
                "option_a" => "a) To administer medication",
                "option_b" => "b) To measure urine output",
                "option_c" => "c) To provide nutrition and medication directly into the stomach",
                "option_d" => "d) To collect stool when a patient cannot use the toilet",
                "correct_answer" => "Answer: c) To provide nutrition and medication directly into the stomach",
                "user_id" => 1
            ]
        ]);
    }
}
